### ISSUE TITLE
Copy format should uppercase all characters

### ISSUE THREAD

**Issue by a2geek** [AppleCommander/bastokenizer#9]

**Comment by a2geek** [comment]
It appears that some IDENT tokens are null strings.

```
$ bt --list src/test/resources/alien-drizzle.bas 
<snip>
Caused by: java.lang.NullPointerException
	at com.webcodepro.applecommander.util.applesoft.Token.ident(Token.java:46)
	at com.webcodepro.applecommander.util.applesoft.TokenReader.next(TokenReader.java:108)
	at com.webcodepro.applecommander.util.applesoft.TokenReader.tokenize(TokenReader.java:51)
	at com.webcodepro.applecommander.util.applesoft.TokenReader.tokenize(TokenReader.java:37)
	at io.github.applecommander.bastokenizer.Main.process(Main.java:103)
	at io.github.applecommander.bastokenizer.Main.call(Main.java:79)
	at io.github.applecommander.bastokenizer.Main.call(Main.java:30)
	at picocli.CommandLine.execute(CommandLine.java:830)
	... 16 more
```
